# -*- coding: utf-8 -*-
"""5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gaUc4obiaqxPnfOBk_Zx3ap1kxwnqEF
"""

from typing import Annotated, Sequence, TypedDict
from langchain_core.messages import (
    BaseMessage,
    HumanMessage,
    SystemMessage
)
from langchain_google_genai import ChatGoogleGenerativeAI

from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import MemorySaver



!pip install -U langchain-google-genai

class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], add_messages]

import os
os.environ['GOOGLE_API_KEY']="AQ.Ab8RN6J9A4J8cuDAzwD9c7fzJzDC0oX-oQ0ELRprXLsRsxCA4g"
model = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0)

def assistant(state: AgentState):

    system_message = SystemMessage(
        content="You are a helpful study assistant. Remember the conversation and answer clearly."
    )

    response = model.invoke(
        [system_message] + list(state["messages"])
    )

    return {
        "messages": [response]
    }

graph = StateGraph(AgentState)

graph.add_node("assistant", assistant)

graph.add_edge(START, "assistant")
graph.add_edge("assistant", END)

memory = MemorySaver()
app = graph.compile(checkpointer=memory)

config = {
    "configurable": {
        "thread_id": "conversation_1"
    }
}
while True:
  user_input=input("you:")
  if user_input.lower() in ["bye","exit"]:
    print("Ai:Goodbye")
    break
  result=app.invoke(
      {
          "messages":[
              HumanMessage(content=user_input)

          ]
      },
      config=config
  )
  print("ai:",result['messages'][-1].content)

